export const REGISTER = "REGISTER";
export const LOGIN = "LOGIN";
export const LOGOUT = "LOGOUT";

export const REGISTER_TAB = "REGISTER_TAB";
export const LOGIN_TAB = "LOGIN_TAB";
export const VEHICLES_TAB = "VEHICLES_TAB";
export const WORK_ORGANIZATION_TAB = "WORK_ORGANIZATION_TAB";
export const EMPLOYEES_TAB = "EMPLOYEES_TAB";
export const DELIVERIES_TAB = "DELIVERIES_TAB";
export const SPECIAL_PERMISSIONS_TAB = "SPECIAL_PERMISSIONS_TAB";
export const CUSTOM_REPORTS_TAB = "CUSTOM_REPORTS_TAB";

export const ERRORS = "ERRORS";
export const ALERT_SHOW = "ALERT_SHOW";
export const ALERT_HIDE = "ALERT_HIDE";

export const MODAL_SHOW = "MODAL_SHOW";
export const MODAL_HIDE = "MODAL_HIDE";

export const SELECT_OPTION = "SELECT_OPTION";

export const LIST_VEHICLES = "LIST_VEHICLES";
export const LIST_VEHICLE_TYPES = "LIST_VEHICLE_TYPES";
export const LIST_WORK_ORGANIZATIONS = "LIST_WORK_ORGANIZATIONS";

export const DELETE_VEHICLE = "DELETE_VEHICLE";
export const UPDATE_VEHICLE = "UPDATE_VEHICLE";
export const CREATE_VEHICLE = "CREATE_VEHICLE";

export const CREATE_WORK_ORGANIZATION = "CREATE_WORK_ORGANIZATION";
export const UPDATE_WORK_ORGANIZATION = "UPDATE_WORK_ORGANIZATION";
export const DELETE_WORK_ORGANIZATION = "DELETE_WORK_ORGANIZATION";

export const LIST_EMPLOYEES = "LIST_EMPLOYEES";
export const CREATE_EMPLOYEE = "CREATE_EMPLOYEE";
export const UPDATE_EMPLOYEE = "UPDATE_EMPLOYEE";
export const DELETE_EMPLOYEE = "DELETE_EMPLOYEE";

export const CREATE_DELIVERY = "CREATE_DELIVERY";
export const LIST_DELIVERIES = "LIST_DELIVERIES";

export const DELIVERYITEMID = "DELIVERYITEMID";
export const SETTIMEIN = "SETTIMEIN";
export const SETTIMEOUT = "SETTIMEOUT";
export const ADDNOTEFIELD = "ADDNOTEFIELD";
export const REMOVENOTEFIELD = "REMOVENOTEFIELD";

export const LIST_PERMISSIONS = "LIST_PERMISSIONS";
export const UPDATE_PERMISSIONS = "UPDATE_PERMISSIONS";

export const LIST_USERS = "LIST_USERS";

export const TIME_IN = "TIME_IN";
export const TIME_OUT = "TIME_OUT";
export const HREF = "HREF";
export const PAGINATION = "PAGINATION";
export const LINKOVI = "LINKOVI";

export const DASHBOARD_TAB = "DASHBOARD_TAB";

export const LIST_ROLES = "LIST_ROLES";